name:                scmpy
version:             0.1.0.0
github:              "Meowcolm024/scmpy"
license:             BSD3
author:              "Malcolm Law"
maintainer:          ":)"
copyright:           "Malcolm Law"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Meowcolm024/scmpy#readme>

dependencies:
- base >= 4.7 && < 5
- parsec

library:
  source-dirs: src

executables:
  scmpy-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scmpy

tests:
  scmpy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scmpy
